version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matrixbreaker
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    entrypoint: /ollama-entrypoint.sh
  backend:
    build: .
    command: ./wait-for-it.sh db 5432 -- flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/app
    ports:
      - "55000:5000"
    depends_on:
      - db
      - ollama
volumes:
  pgdata:
  ollama_data:
